<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Snook.Contracts</AssemblyName>
    <RootNamespace>Snook.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Snook.Domain/Snook.Domain.csproj" />
  </ItemGroup>
</Project>
