<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>snook</AssemblyName>
    <RootNamespace>Snook.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Snook.Application/Snook.Application.csproj" />
    <ProjectReference Include="../Snook.Domain/Snook.Domain.csproj" />
    <ProjectReference Include="../Snook.Persistence.Sqlite/Snook.Persistence.Sqlite.csproj" />
  </ItemGroup>
</Project>
