<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Snook</AssemblyName>
    <RootNamespace>Snook.Desktop</RootNamespace>
    <ApplicationIcon />
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <ProjectReference Include="../Snook.UI/Snook.UI.csproj" />
  </ItemGroup>
</Project>
