<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Snook.Persistence.Sqlite</AssemblyName>
    <RootNamespace>Snook.Persistence.Sqlite</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <ProjectReference Include="../Snook.Domain/Snook.Domain.csproj" />
  </ItemGroup>
</Project>
